Repository zlib-ng/minizip-ng, pull requests merged in 2023-06, with the labels that each got.

#704 Fix cmake install location
  CMakeLists.txt
Labels: build system

#714 Only return MZ_MEM_ERROR if no other error code was received before.
  mz_zip.c
Labels: bug

#721 CMake: fix SONAME for MZ_COMPAT
  CMakeLists.txt
Labels: compatibility, build system
