Repository zlib-ng/minizip-ng, pull requests merged in 2024-11, with the labels that each got.

#820 fix incorrect dos date conversion
  mz_zip.c
Labels: bug

#819 FIx typo in `mz_zip_file.md`
  doc/mz_zip_file.md
Labels: documentation

#823 missing mz_dos_date defines in unzip.h
  compat/unzip.h
Labels: compatibility

#829 Fix and improve fuzzers
  test/fuzz/unzip_fuzzer.c
  test/fuzz/zip_fuzzer.c
Labels: unit tests
